name: absolute_cinema
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  lottie: ^3.3.1
  provider: ^6.1.5
  uuid: ^4.5.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.1.10
  awesome_notifications_core: any
  awesome_notifications_fcm: ^0.10.1
  awesome_notifications: ^0.10.1
  internet_connection_checker_plus: ^2.7.2
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  # image_gallery_saver: ^2.0.3
  permission_handler: ^12.0.0+1
  gal: ^2.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
