// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU5VZF3Aubhmdwge1NqP_5I6hhjCkOAX0',
    appId: '1:328098550725:web:90e057eb3292a5092a71ac',
    messagingSenderId: '328098550725',
    projectId: 'movie-app-6418e',
    authDomain: 'movie-app-6418e.firebaseapp.com',
    storageBucket: 'movie-app-6418e.firebasestorage.app',
    measurementId: 'G-2NQ5Y2Z874',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkKoJ2__9UDlYCPmDAC1BLN2zl-krEvrE',
    appId: '1:328098550725:android:3362b419749401542a71ac',
    messagingSenderId: '328098550725',
    projectId: 'movie-app-6418e',
    storageBucket: 'movie-app-6418e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvioPiwlPr1fRM4Q7VFpysJkKYmCP7F0',
    appId: '1:328098550725:ios:2e4f51fd7f3085112a71ac',
    messagingSenderId: '328098550725',
    projectId: 'movie-app-6418e',
    storageBucket: 'movie-app-6418e.firebasestorage.app',
    iosBundleId: 'com.example.coba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvioPiwlPr1fRM4Q7VFpysJkKYmCP7F0',
    appId: '1:328098550725:ios:2e4f51fd7f3085112a71ac',
    messagingSenderId: '328098550725',
    projectId: 'movie-app-6418e',
    storageBucket: 'movie-app-6418e.firebasestorage.app',
    iosBundleId: 'com.example.coba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU5VZF3Aubhmdwge1NqP_5I6hhjCkOAX0',
    appId: '1:328098550725:web:09b84a68c11447792a71ac',
    messagingSenderId: '328098550725',
    projectId: 'movie-app-6418e',
    authDomain: 'movie-app-6418e.firebaseapp.com',
    storageBucket: 'movie-app-6418e.firebasestorage.app',
    measurementId: 'G-08RSTFSV09',
  );
}
